# Welcome to Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name" : ['Harry', 'Rohan', 'Ayushi', 'Sim'],
    "marks" : [93, 83, 91, 90],
    "city" : ['Jaipur', 'Rampur', 'Agra', 'Kolkata']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     name  marks     city
0   Harry     93   Jaipur
1   Rohan     83   Rampur
2  Ayushi     91     Agra
3     Sim     90  Kolkata

In [5]:
df.to_csv('friend.csv')

In [ ]:
df.to_csv('friend_index_false.csv', index = False)

In [8]:
df.head(2)

    name  marks    city
0  Harry     93  Jaipur
1  Rohan     83  Rampur

In [9]:
df.tail(1)

  name  marks     city
3  Sim     90  Kolkata

In [10]:
df.describe()

           marks
count   4.000000
mean   89.250000
std     4.349329
min    83.000000
25%    88.250000
50%    90.500000
75%    91.500000
max    93.000000

In [11]:
friend = pd.read_csv('friend.csv')

In [12]:
friend

   Unnamed: 0    name  marks     city
0           0   Harry     93   Jaipur
1           1   Rohan     83   Rampur
2           2  Ayushi     91     Agra
3           3     Sim     90  Kolkata

In [13]:
dict2 = {
    "Train No" : [12764, 12845, 12309, 12535],
    "Speed" : [123, 183, 156, 190],
    "city" : ['Jaipur', 'Rampur', 'Agra', 'Kolkata']
}

In [14]:
df2 = pd.DataFrame(dict2)

In [15]:
df2

   Train No  Speed     city
0     12764    123   Jaipur
1     12845    183   Rampur
2     12309    156     Agra
3     12535    190  Kolkata

In [16]:
df2.to_csv('Train.csv')

In [17]:
df2.describe()

           Train No       Speed
count      4.000000    4.000000
mean   12613.250000  163.000000
std      241.609016   30.430248
min    12309.000000  123.000000
25%    12478.500000  147.750000
50%    12649.500000  169.500000
75%    12784.250000  184.750000
max    12845.000000  190.000000

In [18]:
df2['Speed']

0    123
1    183
2    156
3    190
Name: Speed, dtype: int64

In [19]:
df2

   Train No  Speed     city
0     12764    123   Jaipur
1     12845    183   Rampur
2     12309    156     Agra
3     12535    190  Kolkata

In [20]:
df2.index = ['first', 'second', 'third', 'fourth']

In [21]:
df2

        Train No  Speed     city
first      12764    123   Jaipur
second     12845    183   Rampur
third      12309    156     Agra
fourth     12535    190  Kolkata

In [22]:
df2.index = ['1', '2', '3', '4']

In [23]:
df2

   Train No  Speed     city
1     12764    123   Jaipur
2     12845    183   Rampur
3     12309    156     Agra
4     12535    190  Kolkata