# Welcome to Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name" : ['Harry', 'Rohan', 'Ayushi', 'Sim'],
    "marks" : [93, 83, 91, 90],
    "city" : ['Jaipur', 'Rampur', 'Agra', 'Kolkata']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     name  marks     city
0   Harry     93   Jaipur
1   Rohan     83   Rampur
2  Ayushi     91     Agra
3     Sim     90  Kolkata

In [5]:
df.to_csv('friend.csv')

In [ ]:
df.to_csv('friend_index_false.csv', index = False)

In [8]:
df.head(2)

    name  marks    city
0  Harry     93  Jaipur
1  Rohan     83  Rampur

In [9]:
df.tail(1)

  name  marks     city
3  Sim     90  Kolkata

In [10]:
df.describe()

           marks
count   4.000000
mean   89.250000
std     4.349329
min    83.000000
25%    88.250000
50%    90.500000
75%    91.500000
max    93.000000

In [11]:
friend = pd.read_csv('friend.csv')

In [12]:
friend

   Unnamed: 0    name  marks     city
0           0   Harry     93   Jaipur
1           1   Rohan     83   Rampur
2           2  Ayushi     91     Agra
3           3     Sim     90  Kolkata

In [13]:
dict2 = {
    "Train No" : [12764, 12845, 12309, 12535],
    "Speed" : [123, 183, 156, 190],
    "city" : ['Jaipur', 'Rampur', 'Agra', 'Kolkata']
}

In [14]:
df2 = pd.DataFrame(dict2)

In [15]:
df2

   Train No  Speed     city
0     12764    123   Jaipur
1     12845    183   Rampur
2     12309    156     Agra
3     12535    190  Kolkata

In [16]:
df2.to_csv('Train.csv')

In [17]:
df2.describe()

           Train No       Speed
count      4.000000    4.000000
mean   12613.250000  163.000000
std      241.609016   30.430248
min    12309.000000  123.000000
25%    12478.500000  147.750000
50%    12649.500000  169.500000
75%    12784.250000  184.750000
max    12845.000000  190.000000

In [18]:
df2['Speed']

0    123
1    183
2    156
3    190
Name: Speed, dtype: int64

In [19]:
df2

   Train No  Speed     city
0     12764    123   Jaipur
1     12845    183   Rampur
2     12309    156     Agra
3     12535    190  Kolkata

In [20]:
df2.index = ['first', 'second', 'third', 'fourth']

In [21]:
df2

        Train No  Speed     city
first      12764    123   Jaipur
second     12845    183   Rampur
third      12309    156     Agra
fourth     12535    190  Kolkata

In [22]:
df2.index = ['1', '2', '3', '4']

In [23]:
df2

   Train No  Speed     city
1     12764    123   Jaipur
2     12845    183   Rampur
3     12309    156     Agra
4     12535    190  Kolkata

In [24]:
df2[["Train No", "city"]]

   Train No     city
1     12764   Jaipur
2     12845   Rampur
3     12309     Agra
4     12535  Kolkata

In [25]:
df2["Speed"].max()

190

In [26]:
df2["Speed"].mean()

np.float64(163.0)

In [27]:
df2["Speed"].min()

123

In [28]:
df2[df2["Speed"] > 150]

   Train No  Speed     city
2     12845    183   Rampur
3     12309    156     Agra
4     12535    190  Kolkata

In [29]:
df3 = pd.Series(np.random.rand(34))

In [30]:
type(df3)

pandas.core.series.Series

In [31]:
df3 = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))

In [32]:
df3

            0         1         2         3         4
0    0.861095  0.681662  0.499224  0.688652  0.821958
1    0.541093  0.036320  0.887055  0.053544  0.064429
2    0.677482  0.037499  0.227253  0.994950  0.932801
3    0.596865  0.517367  0.509928  0.806529  0.876820
4    0.872229  0.450717  0.158218  0.281046  0.065101
..        ...       ...       ...       ...       ...
329  0.643644  0.660432  0.130806  0.550313  0.742746
330  0.480743  0.126464  0.888178  0.534762  0.415884
331  0.921506  0.955975  0.919688  0.281380  0.819138
332  0.062921  0.870920  0.238555  0.324707  0.436028
333  0.344966  0.313297  0.714687  0.717541  0.729728

[334 rows x 5 columns]

In [33]:
df3.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.527479    0.514627    0.487397    0.453596    0.501339
std      0.282664    0.294351    0.292926    0.282386    0.282849
min      0.004400    0.001736    0.002928    0.002901    0.006009
25%      0.288211    0.264727    0.230571    0.204705    0.246334
50%      0.553410    0.545012    0.462973    0.434905    0.508124
75%      0.747416    0.763700    0.746494    0.674149    0.749508
max      0.997476    0.995835    0.994603    0.999421    0.998875

In [34]:
df3.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [35]:
type(df3)
df3.head()

          0         1         2         3         4
0  0.861095  0.681662  0.499224  0.688652  0.821958
1  0.541093  0.036320  0.887055  0.053544  0.064429
2  0.677482  0.037499  0.227253  0.994950  0.932801
3  0.596865  0.517367  0.509928  0.806529  0.876820
4  0.872229  0.450717  0.158218  0.281046  0.065101

In [37]:
df3[0][0] = "df2"

In [38]:
df3.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [39]:
df3.head()

          0         1         2         3         4
0       df2  0.681662  0.499224  0.688652  0.821958
1  0.541093  0.036320  0.887055  0.053544  0.064429
2  0.677482  0.037499  0.227253  0.994950  0.932801
3  0.596865  0.517367  0.509928  0.806529  0.876820
4  0.872229  0.450717  0.158218  0.281046  0.065101

In [40]:
df3.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [41]:
df3.columns

RangeIndex(start=0, stop=5, step=1)

In [42]:
df3.to_numpy()

array([['df2', 0.6816620853348527, 0.49922366990910083,
        0.688652311033075, 0.8219575754947931],
       [0.5410933761491589, 0.03632046105817288, 0.887055289822718,
        0.053543941979454, 0.06442855616735821],
       [0.6774820792807397, 0.03749859541560163, 0.22725314191218782,
        0.9949498425717291, 0.9328006303536925],
       ...,
       [0.9215062747343836, 0.9559752394058002, 0.919687555943767,
        0.2813797531246034, 0.8191384509061229],
       [0.06292088229321158, 0.8709197234376101, 0.23855467503317818,
        0.3247070881083042, 0.43602785851762804],
       [0.3449655235627669, 0.3132974602425005, 0.7146872400666128,
        0.7175406805754102, 0.7297279688963173]],
      shape=(334, 5), dtype=object)

In [43]:
df3[0][0] = 0.3

In [44]:
df3

            0         1         2         3         4
0         0.3  0.681662  0.499224  0.688652  0.821958
1    0.541093  0.036320  0.887055  0.053544  0.064429
2    0.677482  0.037499  0.227253  0.994950  0.932801
3    0.596865  0.517367  0.509928  0.806529  0.876820
4    0.872229  0.450717  0.158218  0.281046  0.065101
..        ...       ...       ...       ...       ...
329  0.643644  0.660432  0.130806  0.550313  0.742746
330  0.480743  0.126464  0.888178  0.534762  0.415884
331  0.921506  0.955975  0.919688  0.281380  0.819138
332  0.062921  0.870920  0.238555  0.324707  0.436028
333  0.344966  0.313297  0.714687  0.717541  0.729728

[334 rows x 5 columns]

In [45]:
df3.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.541093,0.677482,0.596865,0.872229,0.930873,0.695542,0.416166,0.143489,0.629399,...,0.602724,0.682512,0.599404,0.599175,0.983248,0.643644,0.480743,0.921506,0.062921,0.344966
1,0.681662,0.03632,0.037499,0.517367,0.450717,0.558967,0.53441,0.537005,0.79342,0.710305,...,0.944556,0.697287,0.946071,0.181019,0.658014,0.660432,0.126464,0.955975,0.87092,0.313297
2,0.499224,0.887055,0.227253,0.509928,0.158218,0.795617,0.744302,0.202556,0.954811,0.981615,...,0.145273,0.838675,0.798546,0.512176,0.215778,0.130806,0.888178,0.919688,0.238555,0.714687
3,0.688652,0.053544,0.99495,0.806529,0.281046,0.815872,0.99536,0.070121,0.81006,0.999421,...,0.522686,0.002901,0.144461,0.523907,0.033738,0.550313,0.534762,0.28138,0.324707,0.717541
4,0.821958,0.064429,0.932801,0.87682,0.065101,0.537699,0.680238,0.530835,0.905238,0.071458,...,0.943062,0.667247,0.914072,0.375775,0.66632,0.742746,0.415884,0.819138,0.436028,0.729728

In [46]:
df3

            0         1         2         3         4
0         0.3  0.681662  0.499224  0.688652  0.821958
1    0.541093  0.036320  0.887055  0.053544  0.064429
2    0.677482  0.037499  0.227253  0.994950  0.932801
3    0.596865  0.517367  0.509928  0.806529  0.876820
4    0.872229  0.450717  0.158218  0.281046  0.065101
..        ...       ...       ...       ...       ...
329  0.643644  0.660432  0.130806  0.550313  0.742746
330  0.480743  0.126464  0.888178  0.534762  0.415884
331  0.921506  0.955975  0.919688  0.281380  0.819138
332  0.062921  0.870920  0.238555  0.324707  0.436028
333  0.344966  0.313297  0.714687  0.717541  0.729728

[334 rows x 5 columns]