# Welcome to Pandas

In [119]:
import numpy as np
import pandas as pd

In [120]:
dict1 = {
    "name" : ['Harry', 'Rohan', 'Ayushi', 'Sim'],
    "marks" : [93, 83, 91, 90],
    "city" : ['Jaipur', 'Rampur', 'Agra', 'Kolkata']
}

In [121]:
df = pd.DataFrame(dict1)

In [122]:
df

     name  marks     city
0   Harry     93   Jaipur
1   Rohan     83   Rampur
2  Ayushi     91     Agra
3     Sim     90  Kolkata

In [123]:
df.to_csv('friend.csv')

In [124]:
df.to_csv('friend_index_false.csv', index = False)

In [125]:
df.head(2)

    name  marks    city
0  Harry     93  Jaipur
1  Rohan     83  Rampur

In [126]:
df.tail(1)

  name  marks     city
3  Sim     90  Kolkata

In [127]:
df.describe()

           marks
count   4.000000
mean   89.250000
std     4.349329
min    83.000000
25%    88.250000
50%    90.500000
75%    91.500000
max    93.000000

In [128]:
friend = pd.read_csv('friend.csv')

In [129]:
friend

   Unnamed: 0    name  marks     city
0           0   Harry     93   Jaipur
1           1   Rohan     83   Rampur
2           2  Ayushi     91     Agra
3           3     Sim     90  Kolkata

In [130]:
dict2 = {
    "Train No" : [12764, 12845, 12309, 12535],
    "Speed" : [123, 183, 156, 190],
    "city" : ['Jaipur', 'Rampur', 'Agra', 'Kolkata']
}

In [131]:
df2 = pd.DataFrame(dict2)

In [132]:
df2

   Train No  Speed     city
0     12764    123   Jaipur
1     12845    183   Rampur
2     12309    156     Agra
3     12535    190  Kolkata

In [133]:
df2.to_csv('Train.csv')

In [134]:
df2.describe()

           Train No       Speed
count      4.000000    4.000000
mean   12613.250000  163.000000
std      241.609016   30.430248
min    12309.000000  123.000000
25%    12478.500000  147.750000
50%    12649.500000  169.500000
75%    12784.250000  184.750000
max    12845.000000  190.000000

In [135]:
df2['Speed']

0    123
1    183
2    156
3    190
Name: Speed, dtype: int64

In [136]:
df2

   Train No  Speed     city
0     12764    123   Jaipur
1     12845    183   Rampur
2     12309    156     Agra
3     12535    190  Kolkata

In [137]:
df2.index = ['first', 'second', 'third', 'fourth']

In [138]:
df2

        Train No  Speed     city
first      12764    123   Jaipur
second     12845    183   Rampur
third      12309    156     Agra
fourth     12535    190  Kolkata

In [139]:
df2.index = ['1', '2', '3', '4']

In [140]:
df2

   Train No  Speed     city
1     12764    123   Jaipur
2     12845    183   Rampur
3     12309    156     Agra
4     12535    190  Kolkata

In [141]:
df2[["Train No", "city"]]

   Train No     city
1     12764   Jaipur
2     12845   Rampur
3     12309     Agra
4     12535  Kolkata

In [142]:
df2["Speed"].max()

190

In [143]:
df2["Speed"].mean()

np.float64(163.0)

In [144]:
df2["Speed"].min()

123

In [145]:
df2[df2["Speed"] > 150]

   Train No  Speed     city
2     12845    183   Rampur
3     12309    156     Agra
4     12535    190  Kolkata

In [146]:
df3 = pd.Series(np.random.rand(34))

In [147]:
type(df3)

pandas.core.series.Series

In [148]:
df3 = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))

In [149]:
df3

            0         1         2         3         4
0    0.055414  0.081213  0.552117  0.498578  0.105763
1    0.317698  0.836929  0.528960  0.763906  0.832658
2    0.439609  0.381749  0.917394  0.288957  0.775555
3    0.716884  0.433784  0.113950  0.084175  0.720029
4    0.545759  0.850376  0.247461  0.732546  0.427715
..        ...       ...       ...       ...       ...
329  0.694357  0.602168  0.636195  0.384270  0.710532
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526
332  0.567519  0.700467  0.001868  0.366984  0.476490
333  0.782632  0.081677  0.153602  0.153194  0.752979

[334 rows x 5 columns]

In [150]:
df3.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.506183    0.499129    0.516418    0.497142    0.518635
std      0.284054    0.295689    0.276109    0.287386    0.293489
min      0.002207    0.000223    0.001097    0.000682    0.004907
25%      0.269083    0.216576    0.301130    0.239303    0.241248
50%      0.507737    0.495435    0.531040    0.508809    0.557920
75%      0.746355    0.764464    0.740932    0.744722    0.739288
max      0.998704    0.997161    0.996946    0.993412    0.999904

In [151]:
df3.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [152]:
type(df3)
df3.head()

          0         1         2         3         4
0  0.055414  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555
3  0.716884  0.433784  0.113950  0.084175  0.720029
4  0.545759  0.850376  0.247461  0.732546  0.427715

In [153]:
df3[0][0] = "df2"

C:\Users\simak\AppData\Local\Temp\ipykernel_31668\1253439449.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df3[0][0] = "df2"
C:\Users\simak\AppData\Local\Temp\ipykernel_31668\1253439449.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'df2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df3[0][0] = "df2"

In [154]:
df3.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [155]:
df3.head()

          0         1         2         3         4
0       df2  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555
3  0.716884  0.433784  0.113950  0.084175  0.720029
4  0.545759  0.850376  0.247461  0.732546  0.427715

In [156]:
df3.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [157]:
df3.columns

RangeIndex(start=0, stop=5, step=1)

In [158]:
df3.to_numpy()

array([['df2', 0.08121251974110444, 0.5521170395811421,
        0.4985779287702118, 0.10576253135751323],
       [0.3176976172165602, 0.836928549696845, 0.5289604617818152,
        0.7639058595517032, 0.832657685318215],
       [0.4396086184547183, 0.3817488807323747, 0.9173944680254343,
        0.28895684988316916, 0.7755550207934143],
       ...,
       [0.21188183021341755, 0.4130462248182285, 0.2681972528959434,
        0.7726210141046784, 0.4635259710792696],
       [0.5675194376184708, 0.7004668384050119, 0.0018680627599304556,
        0.366983924726222, 0.4764899094509285],
       [0.7826321548866989, 0.08167732464374466, 0.1536018958097879,
        0.15319377675042434, 0.7529794151658965]],
      shape=(334, 5), dtype=object)

In [159]:
df3[0][0] = 0.3

In [160]:
df3

            0         1         2         3         4
0         0.3  0.081213  0.552117  0.498578  0.105763
1    0.317698  0.836929  0.528960  0.763906  0.832658
2    0.439609  0.381749  0.917394  0.288957  0.775555
3    0.716884  0.433784  0.113950  0.084175  0.720029
4    0.545759  0.850376  0.247461  0.732546  0.427715
..        ...       ...       ...       ...       ...
329  0.694357  0.602168  0.636195  0.384270  0.710532
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526
332  0.567519  0.700467  0.001868  0.366984  0.476490
333  0.782632  0.081677  0.153602  0.153194  0.752979

[334 rows x 5 columns]

In [161]:
df3.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.317698,0.439609,0.716884,0.545759,0.644361,0.395966,0.384901,0.264443,0.700694,...,0.193412,0.158775,0.104264,0.96608,0.890181,0.694357,0.031262,0.211882,0.567519,0.782632
1,0.081213,0.836929,0.381749,0.433784,0.850376,0.118263,0.974401,0.386211,0.145912,0.142189,...,0.238413,0.996448,0.00687,0.209939,0.606477,0.602168,0.369767,0.413046,0.700467,0.081677
2,0.552117,0.52896,0.917394,0.11395,0.247461,0.236064,0.576972,0.877359,0.321019,0.365775,...,0.128887,0.412929,0.091368,0.109949,0.142461,0.636195,0.916603,0.268197,0.001868,0.153602
3,0.498578,0.763906,0.288957,0.084175,0.732546,0.545918,0.526735,0.480723,0.219558,0.04574,...,0.124674,0.153398,0.52856,0.541121,0.903822,0.38427,0.181743,0.772621,0.366984,0.153194
4,0.105763,0.832658,0.775555,0.720029,0.427715,0.964086,0.664366,0.695138,0.365558,0.051496,...,0.027167,0.555015,0.621897,0.074413,0.222566,0.710532,0.381515,0.463526,0.47649,0.752979

In [162]:
df3

            0         1         2         3         4
0         0.3  0.081213  0.552117  0.498578  0.105763
1    0.317698  0.836929  0.528960  0.763906  0.832658
2    0.439609  0.381749  0.917394  0.288957  0.775555
3    0.716884  0.433784  0.113950  0.084175  0.720029
4    0.545759  0.850376  0.247461  0.732546  0.427715
..        ...       ...       ...       ...       ...
329  0.694357  0.602168  0.636195  0.384270  0.710532
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526
332  0.567519  0.700467  0.001868  0.366984  0.476490
333  0.782632  0.081677  0.153602  0.153194  0.752979

[334 rows x 5 columns]

In [163]:
df3.head()

          0         1         2         3         4
0       0.3  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555
3  0.716884  0.433784  0.113950  0.084175  0.720029
4  0.545759  0.850376  0.247461  0.732546  0.427715

In [164]:
df3.sort_index(axis=0, ascending = False)

            0         1         2         3         4
333  0.782632  0.081677  0.153602  0.153194  0.752979
332  0.567519  0.700467  0.001868  0.366984  0.476490
331  0.211882  0.413046  0.268197  0.772621  0.463526
330  0.031262  0.369767  0.916603  0.181743  0.381515
329  0.694357  0.602168  0.636195  0.384270  0.710532
..        ...       ...       ...       ...       ...
4    0.545759  0.850376  0.247461  0.732546  0.427715
3    0.716884  0.433784  0.113950  0.084175  0.720029
2    0.439609  0.381749  0.917394  0.288957  0.775555
1    0.317698  0.836929  0.528960  0.763906  0.832658
0         0.3  0.081213  0.552117  0.498578  0.105763

[334 rows x 5 columns]

In [165]:
df3.sort_index(axis=1, ascending = False)

            4         3         2         1         0
0    0.105763  0.498578  0.552117  0.081213       0.3
1    0.832658  0.763906  0.528960  0.836929  0.317698
2    0.775555  0.288957  0.917394  0.381749  0.439609
3    0.720029  0.084175  0.113950  0.433784  0.716884
4    0.427715  0.732546  0.247461  0.850376  0.545759
..        ...       ...       ...       ...       ...
329  0.710532  0.384270  0.636195  0.602168  0.694357
330  0.381515  0.181743  0.916603  0.369767  0.031262
331  0.463526  0.772621  0.268197  0.413046  0.211882
332  0.476490  0.366984  0.001868  0.700467  0.567519
333  0.752979  0.153194  0.153602  0.081677  0.782632

[334 rows x 5 columns]

In [166]:
df3.head()

          0         1         2         3         4
0       0.3  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555
3  0.716884  0.433784  0.113950  0.084175  0.720029
4  0.545759  0.850376  0.247461  0.732546  0.427715

In [167]:
df3[0]

0           0.3
1      0.317698
2      0.439609
3      0.716884
4      0.545759
         ...
329    0.694357
330    0.031262
331    0.211882
332    0.567519
333    0.782632
Name: 0, Length: 334, dtype: object

In [168]:
type(df3[0])

pandas.core.series.Series

In [169]:
df3_2 = df3

In [170]:
df3_2

            0         1         2         3         4
0         0.3  0.081213  0.552117  0.498578  0.105763
1    0.317698  0.836929  0.528960  0.763906  0.832658
2    0.439609  0.381749  0.917394  0.288957  0.775555
3    0.716884  0.433784  0.113950  0.084175  0.720029
4    0.545759  0.850376  0.247461  0.732546  0.427715
..        ...       ...       ...       ...       ...
329  0.694357  0.602168  0.636195  0.384270  0.710532
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526
332  0.567519  0.700467  0.001868  0.366984  0.476490
333  0.782632  0.081677  0.153602  0.153194  0.752979

[334 rows x 5 columns]

In [171]:
df3_2[0][0] = 9783

In [172]:
df3_2

            0         1         2         3         4
0        9783  0.081213  0.552117  0.498578  0.105763
1    0.317698  0.836929  0.528960  0.763906  0.832658
2    0.439609  0.381749  0.917394  0.288957  0.775555
3    0.716884  0.433784  0.113950  0.084175  0.720029
4    0.545759  0.850376  0.247461  0.732546  0.427715
..        ...       ...       ...       ...       ...
329  0.694357  0.602168  0.636195  0.384270  0.710532
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526
332  0.567519  0.700467  0.001868  0.366984  0.476490
333  0.782632  0.081677  0.153602  0.153194  0.752979

[334 rows x 5 columns]

In [173]:
df3

            0         1         2         3         4
0        9783  0.081213  0.552117  0.498578  0.105763
1    0.317698  0.836929  0.528960  0.763906  0.832658
2    0.439609  0.381749  0.917394  0.288957  0.775555
3    0.716884  0.433784  0.113950  0.084175  0.720029
4    0.545759  0.850376  0.247461  0.732546  0.427715
..        ...       ...       ...       ...       ...
329  0.694357  0.602168  0.636195  0.384270  0.710532
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526
332  0.567519  0.700467  0.001868  0.366984  0.476490
333  0.782632  0.081677  0.153602  0.153194  0.752979

[334 rows x 5 columns]

In [174]:
df3.loc[0,0] = 654

In [175]:
df3.head(2)

          0         1         2         3         4
0       654  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658

In [176]:
df3.columns = list("ABCDE")

In [177]:
df3.head(2)

          A         B         C         D         E
0       654  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658

In [178]:
df3.head()

          A         B         C         D         E
0       654  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555
3  0.716884  0.433784  0.113950  0.084175  0.720029
4  0.545759  0.850376  0.247461  0.732546  0.427715

In [179]:
df3.loc[0, 'A'] = 65445

In [180]:
df3.head()

          A         B         C         D         E
0     65445  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555
3  0.716884  0.433784  0.113950  0.084175  0.720029
4  0.545759  0.850376  0.247461  0.732546  0.427715

In [181]:
df3.loc[[1,2], ['C', 'D']]

          C         D
1  0.528960  0.763906
2  0.917394  0.288957

In [182]:
df3

            A         B         C         D         E
0       65445  0.081213  0.552117  0.498578  0.105763
1    0.317698  0.836929  0.528960  0.763906  0.832658
2    0.439609  0.381749  0.917394  0.288957  0.775555
3    0.716884  0.433784  0.113950  0.084175  0.720029
4    0.545759  0.850376  0.247461  0.732546  0.427715
..        ...       ...       ...       ...       ...
329  0.694357  0.602168  0.636195  0.384270  0.710532
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526
332  0.567519  0.700467  0.001868  0.366984  0.476490
333  0.782632  0.081677  0.153602  0.153194  0.752979

[334 rows x 5 columns]

In [183]:
df3.head()

          A         B         C         D         E
0     65445  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555
3  0.716884  0.433784  0.113950  0.084175  0.720029
4  0.545759  0.850376  0.247461  0.732546  0.427715

In [184]:
df3.loc[:, ['C', 'D']]

            C         D
0    0.552117  0.498578
1    0.528960  0.763906
2    0.917394  0.288957
3    0.113950  0.084175
4    0.247461  0.732546
..        ...       ...
329  0.636195  0.384270
330  0.916603  0.181743
331  0.268197  0.772621
332  0.001868  0.366984
333  0.153602  0.153194

[334 rows x 2 columns]

In [185]:
df3.loc[[1,2], :]

          A         B         C         D         E
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555

In [186]:
df3.loc[(df3['A']<0.3)]

            A         B         C         D         E
8    0.264443  0.145912  0.321019  0.219558  0.365558
23   0.252061  0.537526  0.941164  0.573773  0.575133
27   0.090384  0.679172  0.653832  0.928885  0.797242
30   0.120402  0.727019  0.901654  0.254527  0.588882
31   0.111696  0.404026  0.385461  0.304367  0.195447
..        ...       ...       ...       ...       ...
324  0.193412  0.238413  0.128887  0.124674  0.027167
325  0.158775  0.996448  0.412929  0.153398  0.555015
326  0.104264  0.006870  0.091368  0.528560  0.621897
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526

[92 rows x 5 columns]

In [187]:
df3.loc[(df3 ['A']< 0.3) & (df3['C']> 0.1)]

            A         B         C         D         E
8    0.264443  0.145912  0.321019  0.219558  0.365558
23   0.252061  0.537526  0.941164  0.573773  0.575133
27   0.090384  0.679172  0.653832  0.928885  0.797242
30   0.120402  0.727019  0.901654  0.254527  0.588882
31   0.111696  0.404026  0.385461  0.304367  0.195447
..        ...       ...       ...       ...       ...
317  0.256699  0.564372  0.608220  0.808659  0.158773
324  0.193412  0.238413  0.128887  0.124674  0.027167
325  0.158775  0.996448  0.412929  0.153398  0.555015
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526

[79 rows x 5 columns]

In [188]:
df3.head(2)

          A         B         C         D         E
0     65445  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658

In [189]:
df3.iloc[0,4]

np.float64(0.10576253135751323)

In [190]:
df3.iloc[[0,1], [1,2]]

          B         C
0  0.081213  0.552117
1  0.836929  0.528960

In [191]:
df3.head(3)

          A         B         C         D         E
0     65445  0.081213  0.552117  0.498578  0.105763
1  0.317698  0.836929  0.528960  0.763906  0.832658
2  0.439609  0.381749  0.917394  0.288957  0.775555

In [192]:
df3.drop([0])

            A         B         C         D         E
1    0.317698  0.836929  0.528960  0.763906  0.832658
2    0.439609  0.381749  0.917394  0.288957  0.775555
3    0.716884  0.433784  0.113950  0.084175  0.720029
4    0.545759  0.850376  0.247461  0.732546  0.427715
5    0.644361  0.118263  0.236064  0.545918  0.964086
..        ...       ...       ...       ...       ...
329  0.694357  0.602168  0.636195  0.384270  0.710532
330  0.031262  0.369767  0.916603  0.181743  0.381515
331  0.211882  0.413046  0.268197  0.772621  0.463526
332  0.567519  0.700467  0.001868  0.366984  0.476490
333  0.782632  0.081677  0.153602  0.153194  0.752979

[333 rows x 5 columns]

In [193]:
df3.drop(['A', 'C'], axis = 1)

            B         D         E
0    0.081213  0.498578  0.105763
1    0.836929  0.763906  0.832658
2    0.381749  0.288957  0.775555
3    0.433784  0.084175  0.720029
4    0.850376  0.732546  0.427715
..        ...       ...       ...
329  0.602168  0.384270  0.710532
330  0.369767  0.181743  0.381515
331  0.413046  0.772621  0.463526
332  0.700467  0.366984  0.476490
333  0.081677  0.153194  0.752979

[334 rows x 3 columns]

In [194]:
df3.drop([1,5], axis = 0, inplace = True)

In [195]:
df3.head(3)

          A         B         C         D         E
0     65445  0.081213  0.552117  0.498578  0.105763
2  0.439609  0.381749  0.917394  0.288957  0.775555
3  0.716884  0.433784  0.113950  0.084175  0.720029

In [196]:
df3.reset_index()

     index         A         B         C         D         E
0        0     65445  0.081213  0.552117  0.498578  0.105763
1        2  0.439609  0.381749  0.917394  0.288957  0.775555
2        3  0.716884  0.433784  0.113950  0.084175  0.720029
3        4  0.545759  0.850376  0.247461  0.732546  0.427715
4        6  0.395966  0.974401  0.576972  0.526735  0.664366
..     ...       ...       ...       ...       ...       ...
327    329  0.694357  0.602168  0.636195  0.384270  0.710532
328    330  0.031262  0.369767  0.916603  0.181743  0.381515
329    331  0.211882  0.413046  0.268197  0.772621  0.463526
330    332  0.567519  0.700467  0.001868  0.366984  0.476490
331    333  0.782632  0.081677  0.153602  0.153194  0.752979

[332 rows x 6 columns]

In [197]:
df3.reset_index(drop = True, inplace = True)

In [198]:
df3.head(3)

          A         B         C         D         E
0     65445  0.081213  0.552117  0.498578  0.105763
1  0.439609  0.381749  0.917394  0.288957  0.775555
2  0.716884  0.433784  0.113950  0.084175  0.720029

In [199]:
df3['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [200]:
df3['B'] = None

In [201]:
df3['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
327    True
328    True
329    True
330    True
331    True
Name: B, Length: 332, dtype: bool

In [202]:
df3.loc[:, ['B']] = 56

In [203]:
df3

            A   B         C         D         E
0       65445  56  0.552117  0.498578  0.105763
1    0.439609  56  0.917394  0.288957  0.775555
2    0.716884  56  0.113950  0.084175  0.720029
3    0.545759  56  0.247461  0.732546  0.427715
4    0.395966  56  0.576972  0.526735  0.664366
..        ...  ..       ...       ...       ...
327  0.694357  56  0.636195  0.384270  0.710532
328  0.031262  56  0.916603  0.181743  0.381515
329  0.211882  56  0.268197  0.772621  0.463526
330  0.567519  56  0.001868  0.366984  0.476490
331  0.782632  56  0.153602  0.153194  0.752979

[332 rows x 5 columns]

In [204]:
df3.head()

          A   B         C         D         E
0     65445  56  0.552117  0.498578  0.105763
1  0.439609  56  0.917394  0.288957  0.775555
2  0.716884  56  0.113950  0.084175  0.720029
3  0.545759  56  0.247461  0.732546  0.427715
4  0.395966  56  0.576972  0.526735  0.664366

In [205]:
df = pd.DataFrame(
    {
        "name": ["Alfred", "Batman", "Catwoman"],
        "toy": [np.nan, "Batmobile", "Bullwhip"],
        "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    }
)

In [206]:
df.head()

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [207]:
df.dropna

<bound method DataFrame.dropna of        name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT>

In [208]:
df.dropna(how = 'all')

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [209]:
df.dropna(how = 'all', axis = 1)

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [210]:
dff = pd.DataFrame(
    {
        "name": ["Alfred", "Batman", "Alfred"],
        "toy": [np.nan, "Batmobile", "Bullwhip"],
        "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    }
)

In [211]:
dff

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [212]:
dff.drop_duplicates(subset = ['name'])

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25

In [213]:
dff.drop_duplicates(subset = ['name'], keep = False)

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [214]:
df.shape

(3, 3)

In [215]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [216]:
df['toy'].value_counts(dropna = False)

toy
NaN          1
Batmobile    1
Bullwhip     1
Name: count, dtype: int64

In [217]:
dff.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False

** CREATE A DATAFRAME WHICH CONTAINS ONLY INTEGERS WITH 3 ROWS AND 2 COLUMNS AND THEN RUN SOME METHODS**

In [218]:
import pandas as pd

In [219]:
sa = pd.DataFrame (
    {
        "A" : [1, 2, 3],
        "B" : [4, 5, 6] 
    }
)

print(sa)

   A  B
0  1  4
1  2  5
2  3  6

In [220]:
sa.describe()

         A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

In [221]:
sa.mean()

A    2.0
B    5.0
dtype: float64

In [222]:
sa.corr()

     A    B
A  1.0  1.0
B  1.0  1.0

In [223]:
sa.count()

A    3
B    3
dtype: int64

In [224]:
sa.max()

A    3
B    6
dtype: int64

In [225]:
sa.min()

A    1
B    4
dtype: int64

In [226]:
sa.median()

A    2.0
B    5.0
dtype: float64

In [227]:
sa.std()

A    1.0
B    1.0
dtype: float64

In [228]:
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']
df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [229]:
# Creating DataFrame from the dict of ndarray/lists

import pandas as pd
data = {'Name' : ['Tom', 'Nick', 'Krish', 'Jack'],
        'Age' : [20, 21, 18, 23]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   Nick   21
2  Krish   18
3   Jack   23

In [233]:
data2 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
 
df2 = pd.DataFrame(data2)
 
print(df2[['Name', 'Qualification']])

     Name Qualification
0     Jai           Msc
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd

In [234]:
print(df2[['Name', 'Age', 'Qualification']])

     Name  Age Qualification
0     Jai   27           Msc
1  Princi   24            MA
2  Gaurav   22           MCA
3    Anuj   32           Phd